Repository JGStudy/Alcoholstop, pull requests merged in 2025-03, with the labels that each got.

#5 css 코드 합치기
  css/header.css
  css/main.css
Labels: ✨ feature, 🎨 design

#6 Refactor: 하연 부분 레이아웃 수정
  index.html
Labels: 🐛 bugfix, 🔁 refactor

#7 Refator: 하연 부분 css 수정 및 common.css 공통 폰트 설정
  css/common.css
  css/header.css
Labels: ✨ feature, 🔁 refactor

#26 Refactor: 하연 파트 html 수정
  index.html
Labels: 🐛 bugfix, 🔁 refactor

#27 Feature/24 css 코드 하연 파트 수정
  css/header.css
Labels: ✨ feature, 📄 documentation, 🎨 design

#32 Feature/30 header영역 노션 작동 오류 부분 뜯어고치기
  css/header.css
  index.html
Labels: 🐛 bugfix, 🎨 design

#34 Feature/33 asset icon 파일 추가
  assets/xeicon/fonts/xeicon.eot
  assets/xeicon/fonts/xeicon.svg
  assets/xeicon/fonts/xeicon.ttf
  assets/xeicon/fonts/xeicon.woff
  assets/xeicon/fonts/xeicon.woff2
  assets/xeicon/xeicon.min.css
  css/xeicon.css
  css/xeicon.min.css
  index.html
Labels: 📄 documentation, 🎨 design

#36 Feature/35 header 햄버거버튼 아이콘 수정
  css/header.css
  index.html
Labels: 🎨 design

#40 Feature/38 header 햄버거버튼 클릭이벤트 수정
  css/header.css
  js/header.js
Labels: ✨ feature, 🎨 design

#50 Feature/46 footer css 수정
  assets/images/logo.png
  assets/images/science.png
  css/footer.css
  index.html
Labels: 🎨 design

#53 Feature/41 popup영역 코드 합치기
  assets/images/popup_poster.jpg
  css/popup.css
  index.html
  js/popup.js
Labels: ✨ feature, 🎨 design

#58 Feature/56 선주 푸터 이미지 변경
  assets/images/flogo.svg
  assets/images/flogo01.png
  assets/images/science.png
  assets/images/wa_mark.png
  css/footer.css
  index.html
Labels: 🎨 design

#59 Feature/44 body center 부분 수정
  css/main.css
  index.html
Labels: ✨ feature, 🎨 design

#63 Feature/57 body 영역 스킵 네비게이션 추가
  css/acs.css
  index.html
Labels: ✨ feature

#64 Design: 반응형에 맞춰 헤더 수평라인 수정
  css/header.css
  index.html
Labels: 🎨 design

#65 Feature/37 main 영역 레이아웃 수정
  assets/images/blue_comma.png
  assets/images/link01.svg
  assets/images/link02.svg
  assets/images/link03.svg
  assets/images/link04.svg
  assets/images/link05.svg
  css/main.css
  index.html
  js/main.js
Labels: ✨ feature, 🐛 bugfix, 🎨 design

#67 Feature/66 전체 레이아웃 수정
  css/footer.css
  css/header.css
  css/main.css
  index.html
Labels: 🐛 bugfix, 📄 documentation, 🎨 design

#73 Feature/72 하연 파트 코드 리팩토링
  css/header.css
  css/popup.css
  index.html
Labels: 📄 documentation, 🔁 refactor

#76 Feature/75 top service 화살표 토글 반전
  css/header.css
  js/header.js
Labels: ✨ feature, 🎨 design

#79 Feature/62 main 영역 반응형 추가
  css/main.css
Labels: ✨ feature, 📄 documentation

#83 Feature/82 main 영역 미디어쿼리 수정
  css/main.css
Labels: 🎨 design

#84 Feature/81 header 주석 추가 및 css 수정
  css/header.css
  js/header.js
Labels: 📄 documentation, 🎨 design
